  export BROWSER=chromium
  export DEFAULT=SESSION i3
  export EDITOR=nvim
  export GDK_DPI_SCALE=0.5
  export GDK_SCALE=2
  export GOPATH=$HOME/go
  export GTK2_RC_FILES=$HOME/.gtkrc-2.0
  export PAGER=less
  export PATH=$HOME/bin:$HOME/bin/node_modules/bin:$HOME/go/bin::$PATH
  export RUST_SRC_PATH=$HOME/repos/rust/src/
  export STEAM_FRAME_FORCE_CLOSE=1
  export TERMINAL=st
  export XDG_CONFIG_HOME=$HOME/.config
